### PR TITLE
init: build api and register api protocol

### PR DESCRIPTION
**Pull request by yorkie**
This *feature-request* PR did the following items:

- run the gulp task "cp-apisrc" before running the "fireball"
- register the "api://" protocol for api source directory

This one is working with https://github.com/fireball-packages/code-editor/pull/3

R=@nantas @jwu 
/cc @jareguo

### CODE REVIEW

**Comment by yorkie** [comment]
I'm quite not sure if this is an exact correct way to address the issue which pointed out by @jareguo at https://github.com/fireball-x/engine-framework/pull/32, so I need your thoughts about this problem.

**Comment by jwu** [comment]
Hi @yorkie , Why not use `Editor.url('app://utils/api/...')` instead? Is this can achieve the same thing?

**Comment by yorkie** [comment]
Oh yea, sure. I will remove the code of registering the api protocol in this PR.

**Comment by yorkie** [comment]
Done, now I just run "cp-apisrc" before starting "fireball", does this good to you?

**Comment by nantas** [comment]
Copy api srouce seems alright for me. I just need to include that folder in release version. @jwu thoughts?

**Comment by jwu** [comment]
no problem

**Comment by yorkie** [comment]
Ok, let me do squash commits

**Comment by yorkie** [comment]
Done, thank you guys :)

**Comment by jareguo** [comment]
@yorkie 你 squash 后是不是要 force push 一次？

**Comment by yorkie** [comment]
嗯 如果之前有push到服务器过 就需要force push啦，有啥问题吗？我是在我自己的分支做的～

**Comment by jareguo** [comment]
没问题，我觉得你做得很好，我们应该向你学习

**Comment by yorkie** [comment]
:p :star2:

**Pull request merged**
